banco.url: "http://localhost:8080/beercoins/"

server:
  port: 8083

spring:
   profiles: prod

   rabbitmq:
      addresses: amqps://uykzmnzp:H-oC5AMy3wvGoYTrV01dWEqwu8sdciDm@woodpecker.rmq.cloudamqp.com/uykzmnzp
